services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sitcon-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./data/sitcon.db
      - S3_ENDPOINT=http://minio:9000
      - S3_ACCESS_KEY=minioadmin
      - S3_SECRET_KEY=minioadmin
      - S3_SECURE=false
    env_file:
      - backend.env
    volumes:
      - backend_data:/app/data
    networks:
      - sitcon-network
    depends_on:
      - minio
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    develop:
      watch:
        - action: sync+restart
          path: ./backend/src
          target: /app/src
          ignore:
            - __pycache__/
            - "*.pyc"
            - "*.pyo"
            - .pytest_cache/
        - action: rebuild
          path: ./backend/pyproject.toml
        - action: rebuild
          path: ./backend/main.py

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: sitcon-frontend
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NEXT_PUBLIC_API_URL=http://localhost:8000
  #     - NODE_ENV=development
  #     - NEXT_TELEMETRY_DISABLED=1
  #   env_file:
  #     - frontend.env
  #   networks:
  #     - sitcon-network
  #   depends_on:
  #     - backend
  #   restart: unless-stopped
  #   develop:
  #     watch:
  #       - action: sync
  #         path: ./frontend/src
  #         target: /app/src
  #         ignore:
  #           - node_modules/
  #           - .next/
  #           - .git/
  #       - action: sync
  #         path: ./frontend/next.config.ts
  #         target: /app/next.config.ts
  #       - action: sync
  #         path: ./frontend/tsconfig.json
  #         target: /app/tsconfig.json
  #       - action: sync
  #         path: ./frontend/postcss.config.mjs
  #         target: /app/postcss.config.mjs
  #       - action: sync
  #         path: ./frontend/components.json
  #         target: /app/components.json
  #       - action: rebuild
  #         path: ./frontend/package.json
  #       - action: rebuild
  #         path: ./frontend/pnpm-lock.yaml

  minio:
    image: minio/minio:latest
    container_name: sitcon-minio
    hostname: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    networks:
      - sitcon-network
    command: server /data --console-address ":9001"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  backend_data:
    driver: local
  
  minio_data:
    driver: local

networks:
  sitcon-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16